To rapidly acquaint the intern with the provided dataset and master the critical first step of any analysis: acquiring, cleaning, and preparing data
for analysis. **bold text**

In [2]:
import numpy  as np
import pandas as pd

In [13]:

df =pd.read_csv('messy_dataset.csv')

In [14]:
df.head()

   Customer_ID   Age  Gender  Purchase_Amount    City Subscription
0            1  25.0    Male            200.0    Pune          Yes
1            2  30.0  Female            500.0  Mumbai           No
2            3   NaN  Female            300.0   Delhi          NaN
3            4  45.0     NaN              NaN    Pune          Yes
4            5  22.0    Male            150.0     NaN           No

In [15]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      20 non-null     int64
 1   Age              16 non-null     float64
 2   Gender           17 non-null     object
 3   Purchase_Amount  16 non-null     float64
 4   City             17 non-null     object
 5   Subscription     16 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [16]:
df.shape

(20, 6)

In [17]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Purchase_Amount', 'City',
       'Subscription'],
      dtype='object')

In [18]:
df.isnull()

    Customer_ID    Age  Gender  Purchase_Amount   City  Subscription
0         False  False   False            False  False         False
1         False  False   False            False  False         False
2         False   True   False            False  False          True
3         False  False    True             True  False         False
4         False  False   False            False   True         False
5         False  False   False            False  False         False
6         False  False   False            False  False         False
7         False   True   False            False  False          True
8         False  False   False             True  False         False
9         False  False    True            False  False         False
10        False  False   False            False  False         False
11        False  False   False            False  False         False
12        False   True   False            False   True         False
13        False  False   False             True  False          True
14        False  False    True            False  False         False
15        False  False   False            False  False         False
16        False  False   False            False  False         False
17        False  False   False            False  False         False
18        False   True   False            False   True         False
19        False  False   False             True  False          True

In [19]:
# Check missing values
df.isnull().sum()

Customer_ID        0
Age                4
Gender             3
Purchase_Amount    4
City               3
Subscription       4
dtype: int64

In [24]:
df.describe()

       Customer_ID        Age  Purchase_Amount
count     20.00000   16.00000        16.000000
mean      10.50000   39.75000       935.625000
std        5.91608   30.08765      2418.839856
min        1.00000   22.00000       150.000000
25%        5.75000   27.75000       287.500000
50%       10.50000   32.00000       335.000000
75%       15.25000   38.50000       402.500000
max       20.00000  150.00000     10000.000000

In [26]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [27]:
df['Age']

0      25.0
1      30.0
2      32.0
3      45.0
4      22.0
5     150.0
6      35.0
7      32.0
8      28.0
9      40.0
10     29.0
11     31.0
12     32.0
13     27.0
14     33.0
15     38.0
16     41.0
17     26.0
18     32.0
19     36.0
Name: Age, dtype: float64

In [30]:

df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Gender']

0       Male
1     Female
2     Female
3       Male
4       Male
5       Male
6     Female
7     Female
8       Male
9       Male
10    Female
11      Male
12      Male
13    Female
14      Male
15      Male
16    Female
17      Male
18    Female
19      Male
Name: Gender, dtype: object

In [32]:
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())
df['Purchase_Amount']

0       200.0
1       500.0
2       300.0
3       335.0
4       150.0
5     10000.0
6       250.0
7       400.0
8       335.0
9       350.0
10      280.0
11      320.0
12      450.0
13      335.0
14      390.0
15      410.0
16      370.0
17      290.0
18      310.0
19      335.0
Name: Purchase_Amount, dtype: float64

In [33]:
df['City'] = df['City'].fillna(df['City'].mode()[0])
df['City']

0       Pune
1     Mumbai
2      Delhi
3       Pune
4     Mumbai
5     Mumbai
6      Delhi
7       Pune
8     Mumbai
9      Delhi
10      Pune
11    Mumbai
12    Mumbai
13     Delhi
14      Pune
15    Mumbai
16     Delhi
17      Pune
18    Mumbai
19    Mumbai
Name: City, dtype: object

In [34]:
df['Subscription'] = df['Subscription'].fillna(df['Subscription'].mode()[0])
df['Subscription']

0     Yes
1      No
2     Yes
3     Yes
4      No
5     Yes
6     Yes
7     Yes
8      No
9     Yes
10     No
11    Yes
12     No
13    Yes
14    Yes
15     No
16    Yes
17     No
18    Yes
19    Yes
Name: Subscription, dtype: object

In [35]:
df.isnull().sum()

Customer_ID        0
Age                0
Gender             0
Purchase_Amount    0
City               0
Subscription       0
dtype: int64

In [36]:
df.head()

   Customer_ID   Age  Gender  Purchase_Amount    City Subscription
0            1  25.0    Male            200.0    Pune          Yes
1            2  30.0  Female            500.0  Mumbai           No
2            3  32.0  Female            300.0   Delhi          Yes
3            4  45.0    Male            335.0    Pune          Yes
4            5  22.0    Male            150.0  Mumbai           No